[build]
  base    = "vite-project"      # Netlify cambia a esta carpeta
  command = "npm run build"     # Se ejecuta dentro de "vite-project"
  publish = "dist"              # CORRECTO: "dist" está directamente dentro de "vite-project"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200